### PR TITLE
Fix string parsing when string has quotes

### PR DESCRIPTION
**Pull request by adhurjatylull**

### CODE REVIEW

**Comment by paulboocock** [comment]
Thanks for the PR! We need to update the release process for this library as we haven't updated it for a little while. I'll add it to our backlog to sort it and get this released. It'll likely be in November before we get to this due to existing commitments.

**Comment by RobertJamesEllison** [comment]
Hi @paulboocock,
Are there plans to include this fix? We are encountering quite a few of these errors when migrating over our legacy GA events that contain `"` in the fields. 
Also, the package on Nuget is showing as `deprecated`. Is this correct?
Thanks

**Comment by alexanderdean** [comment]
Looping in @jbeemster

**Review by matus-tomlein — APPROVED** [review]
Thanks again for this contribution! Sorry this has taken so long to review, we have just been able to test and will to aim to make a release in the following days.

**Comment by miike** [comment]
@matus-tomlein We don't have a signed CLA yet for this user so are we able to hold back on releasing this.

@adhurjatylull Could you please sign the CLA when you get an opportunity and we can get this released?

https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/

**Pull request merged**
